# Generated by Django 4.1.5 on 2023-02-03 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contestant',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('toph_handle', models.CharField(max_length=100, null=True)),
                ('cf_handle', models.CharField(max_length=100, null=True)),
                ('cc_handle', models.CharField(max_length=100, null=True)),
                ('atcoder_handle', models.CharField(max_length=100, null=True)),
                ('loj_handle', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='atcoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=10000, null=True)),
                ('last_update_time', models.TimeField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingClub.contestant')),
            ],
        ),
    ]
