# Generated by Django 4.1.5 on 2023-02-04 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contestant',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('toph_handle', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('cf_handle', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('cc_handle', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('atcoder_handle', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('loj_handle', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='toph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('last_update_time', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingClub.contestant')),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='ProgrammingClub.contestant')),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='ProgrammingClub.contestant')),
                ('member3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member3', to='ProgrammingClub.contestant')),
            ],
        ),
        migrations.CreateModel(
            name='lightoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('last_update_time', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingClub.contestant')),
            ],
        ),
        migrations.CreateModel(
            name='codeforces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('last_update_time', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingClub.contestant')),
            ],
        ),
        migrations.CreateModel(
            name='codechef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('last_update_time', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingClub.contestant')),
            ],
        ),
        migrations.CreateModel(
            name='atcoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('last_update_time', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingClub.contestant')),
            ],
        ),
    ]
