# Generated by Django 4.1.5 on 2023-02-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammingClub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resent_datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=10)),
                ('date', models.CharField(default='<built-in method now of type object at 0x00007FF8FB038980>', max_length=200)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProgrammingClub.contestant')),
            ],
        ),
    ]
