# Generated by Django 4.1.5 on 2023-02-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammingClub', '0002_resent_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resent_datas',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
