# Generated by Django 4.1.5 on 2023-02-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammingClub', '0002_toph_lightoj_codeforces_codechef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcoder',
            name='last_update_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='codechef',
            name='last_update_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='codeforces',
            name='last_update_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lightoj',
            name='last_update_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='toph',
            name='last_update_time',
            field=models.DateTimeField(),
        ),
    ]
