# Generated by Django 4.1.5 on 2023-02-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammingClub', '0003_alter_resent_datas_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resent_datas',
            name='solved',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resent_datas',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
