# Generated by Django 4.1.5 on 2023-03-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammingClub', '0004_resent_datas_solved_alter_resent_datas_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='user_email',
            field=models.EmailField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
