# Generated by Django 4.1.5 on 2023-02-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammingClub', '0004_alter_atcoder_info_alter_codechef_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='sname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
