# Generated by Django 4.1.5 on 2023-02-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammingClub', '0005_contestant_sname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='sname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
