# Generated by Django 4.1.5 on 2023-03-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammingClub', '0006_coach_contestant_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='coach',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='coach', to='ProgrammingClub.coach'),
        ),
    ]
